# Generated by Django 4.0.3 on 2022-03-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_employee_options_employee_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='root',
            field=models.BooleanField(default=False),
        ),
    ]
